// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://logriuxcaqyvbucvpmgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZ3JpdXhjYXF5dmJ1Y3ZwbWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjI0MDIsImV4cCI6MjA2NDQ5ODQwMn0._ng02f80mTS8vKZXnIyC5jfGtOvrM29op2VSD0b4HVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);